Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using NARANJA.Data;
using NARANJA.Models;

namespace NARANJA.Controllers
{
    public class AdministradorController : Controller
    {
        private readonly ILogger<AdministradorController> _logger;
        
        private readonly ApplicationDbContext _context;

        public AdministradorController(ILogger<AdministradorController> logger,
        ApplicationDbContext context)
        {
            _logger = logger;
            _context=context;
        }
         public IActionResult Index()
        {
            return View();
        }

        public IActionResult Carta()
        {
            return View();
        }
         public IActionResult Reservas()
        { 
           

            var listreservas = _context.Reservas.ToList();
            ViewData["message"]="";
            return View(listreservas);
        }
         public IActionResult Horario()
        {
            return View();
        }
        public IActionResult Miperfil()
        {
            return View();
        }
    }
}

Controllers/ClienteController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

  
  namespace NARANJA.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ILogger<ClienteController> _logger;

        public ClienteController(ILogger<ClienteController> logger)
        {
            _logger = logger;
        }
    public IActionResult PagoCliente()
        {
            return View();
        }
     public IActionResult BoletaCliente()
        {
            return View();
        }
         public IActionResult CartaCliente()
        {
            return View();
        }
         public IActionResult Combo()
        {
            return View();
        }
         public IActionResult EspecialidadesCliente()
        {
            return View();
        }
         public IActionResult OfertaCliente()
        {
            return View();
        }
         public IActionResult ReservaCliente()
        {
            return View();
        }

        
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/PlatosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

using NARANJA.Data;
using NARANJA.Models;
namespace NARANJA.Controllers
{
    public class PlatosController :Controller
    {
        
        private readonly ILogger<PlatosController> _logger;
        
        private readonly ApplicationDbContext _context;

        public PlatosController(ILogger<PlatosController> logger,
        ApplicationDbContext context)
        {
            _logger = logger;
            _context=context;
        }

        public IActionResult Platos()
        { 
            var listplatos = _context.Platos.ToList();
            ViewData["message"]="";
            return View(listplatos);
        }
        
         
    }
}

Views/Shared/DIsplayTemplates.cshtml
@model DateTime
@Model.ToString("dd MMMM, yyyy")

Views/Shared/LayoutCliente.cshtml
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/464243d498.js" crossorigin="anonymous"></script>
   
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NARANJA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Cliente.css" />
    
</head>
<style>
    header{background-color: black;}
</style>
<body>
    
    <header>
       <nav class="navbar fixed-top navbar-black bg-black navbar-expand-sm navbar-toggleable-sm   border-bottom box-shadow mb-3" id="navegador">
  
            <div class="navbar-collapse  d-sm-inline-flex justify-content-around" id="lista">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="BoletaCliente">Boleta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="CartaCliente">Carta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="Combo">Combos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="EspecialidadesCliente">Especialidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="OfertaCliente">Ofertas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="PagoCliente">Pago</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="ReservaCliente">Reserva</a>
                        </li>
                    </ul>
                    
                </div>
        </nav>
        
        <div class="wave" style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
                style="height: 100%; width: 100%;">
                <path d="M0.00,49.98 C150.00,150.00 349.20,-50.00 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"
                    style="stroke: none; fill: #fff;"></path>
            </svg></div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="foot" >
        <div class="container">
             <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Telefono</h4>
                <p>987654321</p>
            </div>
            <div class="content-foo">
                <h4>Email</h4>
                <p>Computec@gmail.com</p>
            </div>
            <div class="content-foo">
                <h4>Localización</h4>
                <p>Av. Ejército 793, Cayma, Arequipa</p>
            </div>
            <div class="content-foo">
                <h4>Redes sociales</h4>
                <div class="social-media">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>
        
           <p id="foot1" class="text-center"> &copy; 2021 - NARANJA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/464243d498.js" crossorigin="anonymous"></script>
    
   
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NARANJA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
   
    
</head>
<style>
    header{background-color: black;}
</style>
<body>
    
    <header>
       <nav class="navbar fixed-top navbar-black bg-black navbar-expand-sm navbar-toggleable-sm   border-bottom box-shadow mb-3" id="navegador">
  
    
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" alt="" style="width: 100px; height:30px ;"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="lista">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Administrador" asp-action="Carta">Carta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Home" asp-action="Nosotros">Nosotros</a>
                        </li>
                        <li class="nav-item">
                        </li>
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Administrador" asp-action="Index">Administrador</a>

                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="No-Cliente" asp-action="Contacto">Contactanos</a>

                        </li>
                  
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
        </nav>
        
        <div class="wave" style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
                style="height: 100%; width: 100%;">
                <path d="M0.00,49.98 C150.00,150.00 349.20,-50.00 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"
                    style="stroke: none; fill: #fff;"></path>
            </svg></div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="foot" >
        <div class="container">
             <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Telefono</h4>
                <p>987654321</p>
            </div>
            <div class="content-foo">
                <h4>Email</h4>
                <p>Tiaveneno@gmail.com</p>
            </div>
            <div class="content-foo">
                <h4>Localización</h4>
                <p>Av. Ejército 793, Cayma, Arequipa</p>
            </div>
            <div class="content-foo">
                <h4>Horario de Atencion</h4>
                <p>Lunes a Miercoles: 11:00 h - 16:00 h </p>
                <p>Miercoles a viernes: 9:00 h - 17:00 h </p>
                <p>sabado a Domingo: 9:00 h - 20:00 h </p>
            </div>
            <div class="content-foo">
                <h4>Redes sociales</h4>
                <div class="social-media">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>
        
           <p id="foot1" class="text-center"> &copy; 2021 - NARANJA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_LayoutAdministrador.cshtml
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/464243d498.js" crossorigin="anonymous"></script>
   
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NARANJA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<style>
    header{background-color: black;}
</style>
<body>
    
    <header>
       <nav class="navbar fixed-top navbar-black bg-black navbar-expand-sm navbar-toggleable-sm   border-bottom box-shadow mb-3" id="navegador">
  
            <div class="navbar-collapse  d-sm-inline-flex justify-content-around" id="lista">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Administrador" asp-action="Carta">Carta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Administrador" asp-action="Horario">Horario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Reservas" asp-action="Reservas">Reservas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Administrador" asp-action="Miperfil">Mi perfil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Platos" asp-action="Platos">Mi perfil</a>
                        </li>
                    </ul>
                    
                </div>
        </nav>
        
        <div class="wave" style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
                style="height: 100%; width: 100%;">
                <path d="M0.00,49.98 C150.00,150.00 349.20,-50.00 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"
                    style="stroke: none; fill: #fff;"></path>
            </svg></div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="foot" >
        <div class="container">
             <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Telefono</h4>
                <p>987654321</p>
            </div>
            <div class="content-foo">
                <h4>Email</h4>
                <p>Computec@gmail.com</p>
            </div>
            <div class="content-foo">
                <h4>Localización</h4>
                <p>Av. Ejército 793, Cayma, Arequipa</p>
            </div>
            <div class="content-foo">
                <h4>Horario de Atencion</h4>
                <p>Lunes a Miercoles: 11:00 h - 16:00 h </p>
                <p>Miercoles a viernes: 9:00 h - 17:00 h </p>
                <p>sabado a Domingo: 9:00 h - 20:00 h </p>
            </div>
            <div class="content-foo">
                <h4>Redes sociales</h4>
                <div class="social-media">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>
        
           <p id="foot1" class="text-center"> &copy; 2021 - NARANJA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_LayoutCliente.cshtml
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/464243d498.js" crossorigin="anonymous"></script>
   
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NARANJA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/cliente.css" />
    
</head>
<style>
    header{background-color: black;}
</style>
<body>
    
    <header>
       <nav class="navbar fixed-top navbar-black bg-black navbar-expand-sm navbar-toggleable-sm   border-bottom box-shadow mb-3" id="navegador">
  
            <div class="navbar-collapse  d-sm-inline-flex justify-content-around" id="lista">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="BoletaCliente">Boleta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="CartaCliente">Carta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="Combo">Combos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="EspecialidadesCliente">Especialidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="OfertaCliente">Ofertas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Cliente" asp-action="PagoCliente">Pago</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-area="" asp-controller="Reservas" asp-action="CrearReserva">Reserva</a>
                        </li>
                    </ul>
                    
                </div>
        </nav>
        
        <div class="wave" style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
                style="height: 100%; width: 100%;">
                <path d="M0.00,49.98 C150.00,150.00 349.20,-50.00 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"
                    style="stroke: none; fill: #fff;"></path>
            </svg></div>
    </header>

    <div class="fondo">

    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="foot" >
        <div class="container">
             <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Telefono</h4>
                <p>987654321</p>
            </div>
            <div class="content-foo">
                <h4>Email</h4>
                <p>Computec@gmail.com</p>
            </div>
            <div class="content-foo">
                <h4>Localización</h4>
                <p>Av. Ejército 793, Cayma, Arequipa</p>
            </div>
            <div class="content-foo">
                <h4>Horario de Atencion</h4>
                <p>Lunes a Miercoles: 11:00 h - 16:00 h </p>
                <p>Miercoles a viernes: 9:00 h - 17:00 h </p>
                <p>sabado a Domingo: 9:00 h - 20:00 h </p>
            </div>
            <div class="content-foo">
                <h4>Redes sociales</h4>
                <div class="social-media">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>
        
           <p id="foot1" class="text-center"> &copy; 2021 - NARANJA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>